services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=user-auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"
